import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loader from "./loading";
import { BText4 } from "@/components/textComponents/BText4";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PARDON",
  description: "Generated by PARDON"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <Suspense fallback={<Loader />}>
          {children}
          <footer className="flex w-full items-center justify-center space-x-8 bg-black">
            <div className="flex flex-row">
              <BText4>
                Created by
                <a
                  href="https://github.com/itsHampus"
                  target="_blank"
                  className="pl-2 hover:text-red-700"
                >
                  @itsHampus
                </a>
              </BText4>
            </div>
            <BText4>&copy; 2024 PARDON. All rights reserved.</BText4>
            <BText4 className="hover:text-red-700">
              <a href="/licenses">Licenses</a>
            </BText4>
          </footer>
        </Suspense>
      </body>
    </html>
  );
}
